name: my first workflow |shell script
on:
    push:
      branches:
          - main

jobs:
    first_job:
        runs-on: self-hosted
        steps:
            - name: list files
              run: ./script.sh
    
    